baseURL = 'https://m-kloeckner.github.io/'
#languageCode = 'en-us'
defaultContentLanguage = "en"
#title = 'My New Hugo Site'
theme = "hallo"
publishDir = "public"

[Author]
    name = "Martin Klöckner"

[params]
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/mkloeckner/"
    [[params.links]]
        icon = "xing"
        title = "Xing"
        url = "https://www.xing.com/profile/Martin_Kloeckner5"
    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/m-kloeckner"
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://www.instagram.com/mkloeckner"
    [params.colors]
        background = "#99acc9"
        foreground = "#edf7ff"
        hover = "#798291"

defaultContentLanguageInSubdir = true
[languages]
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'Home | Martin Klöckner'
    weight = 1
    [languages.de.params]
      subtitle = 'IT Sicherheits-Experte, Blog'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Home | Martin Klöckner'
    weight = 2
    [languages.en.params]
      subtitle = 'Cyber Security Expert, Blog'
