baseURL = 'https://m-kloeckner.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hallo"
publishDir = "docs"

[Author]
    name = "Martin Klöckner"

[params]
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/mkloeckner/"
    [[params.links]]
        icon = "xing"
        title = "Xing"
        url = "https://www.xing.com/profile/Martin_Kloeckner5"
    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/m-kloeckner"
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://www.instagram.com/mkloeckner"
