baseURL = 'https://m-kloeckner.github.io/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'My New Hugo Site'
theme = "hallo"
publishDir = "docs"

[Author]
    name = "Martin Klöckner"

[params]
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/mkloeckner/"
    [[params.links]]
        icon = "xing"
        title = "Xing"
        url = "https://www.xing.com/profile/Martin_Kloeckner5"
    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/m-kloeckner"
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://www.instagram.com/mkloeckner"


defaultContentLanguageInSubdir = true
[languages]
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'Projekt Dokumentation'
    weight = 1
    [languages.de.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
